### ISSUE TITLE
send a request doesn't wait for the request to finish before continuing

### ISSUE THREAD

**Issue by PhilFinachi** [btk5h/reqn#1]
```
send a request to "google.com"
set {_h} to last http response
```
sometimes/often times {_h} isn't the request from the first line but rather the one before it. pls make it wait for the request to finish before continuing, or add the ability to do something like `set {_h} to send a request to "google.com"`

**Comment by btk5h** [comment]
Please post a script that can be used to replicate this bug (preferably in a command).

**Comment by PhilFinachi** [comment]
```
options:
    time: https://script.google.com/macros/s/AKfycbyd5AcbAnWi2Yn0xhFRbyzS4qMq1VucMVgVvhul5XqS9HkAyJY/exe

function getTime(i: integer = 0) :: objects:
  send a request to "{@time}"
  set {_t} to last http response
  set {_u::*} to split content of json value "fulldate" from text "%{_t}'s body%" at " +"
  set {_t::1} to {_u::1}
  set {_t::2} to content of json value "timezone" from text "%{_t}'s body%"
  return {_t::*}
  
command /test:
  trigger:
    set {_t::*} to getTime()
    broadcast "%{_t::*}%"
```
after you reload the skript, the first /test will broadcast `<none>` the first time its run, then it will show the response from the last time for the rest of the times that the command is run

**Comment by btk5h** [comment]
This is an issue with Skript's functions, not with Reqn. It appears that Skript's functions do not work properly if they contain delayed effects.

**Comment by PhilFinachi** [comment]
i know that skript does wait if you are setting a variable to something. would it be possible to work around this by adding something like `set {_t} to send a request to "website"`?

**Comment by btk5h** [comment]
No. You're asking me to rewrite the effect as synchronous (meaning it would block the server until the response arrives).

You should file an issue with Skript and avoid using functions in the meantime.
