### ISSUE TITLE
Broken with amperstand symbol (&)

### ISSUE THREAD

**Issue by XfedeX** [btk5h/reqn#15]
If i use amperstand symobol (&) in link, the web server recieves` \xA7` instead of `&`.
Can you help me to fix this?

**Comment by btk5h** [comment]
This is because Skript is encoding & into chat colors. You can work around this using a function to convert the URL back 
```text
function url(s: string) :: string:
  replace all "§" in {_s} with "&"
  return {_s}
```

**Comment by XfedeX** [comment]
THANKS! THANKS! THANKS! THANK YOU SO MUCH! You now got another star :)

**Comment by XfedeX** [comment]
And can you please add this in the main page with examples so other people won't have this bug?
