### ISSUE TITLE
Request isn't sent and no error appears. Unsure what's happening

### ISSUE THREAD

**Issue by TheMeq** [btk5h/reqn#2]
My code is below, nothing appears to send from the server and nothing is recieved on the other end.

`
command /auth:

    trigger:

        set {_rnd} to random integer from 1 to 4096

        set {_prehash} to hashed "RST%player%RST%now%%{_rnd}%"

        set {_hash} to the first 12 characters of "%{_prehash}%"

        set {_name} to "%name of player%"

        set {_uuid} to the uuid of player

        set {_sname} to url safe {_name}

        set {_suuid} to url safe {_uuid}

        set {_shash} to url safe {_hash}

        set {_url} to "http://auth.redstonetor.ch/upload_details.php?n=%{_sname}%&u=%{_suuid}%&p=%{_shash}%"

        send request to {_url}

        message "Thanks for authenticating your Minecraft account %{_name}%!%nl%%nl%Your one time key is%nl%%nl%-[ &l%{_hash}%&r ]-%nl%%nl%Please enter this code into the key box.%nl%%{_url}%%nl%%{_temp}%"`

**Comment by Moondev0607** [comment]
How did you solve this?
