### ISSUE TITLE
Request is broken

### ISSUE THREAD

**Issue by kierandrewett** [btk5h/reqn#7]
I keep getting this as a response in my request help,

`<html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    Invalid HTTP Version &#x27;Invalid HTTP Version: &#x27;Blue - Rise ft. Jack &amp; Jack&amp;text_only=no HTTP/1.0&#x27;&#x27;
  </body>
</html>`

`Status Code: 400`

`send a request to "https://api.ksoft.si/lyrics/search?q=Jonas Blue - Rise ft. Jack & Jack&text_only=no" with headers "User-Agent: Ender", "Content-Type: application/json" and "Authorization: Token ---"
map json last response's body to {_lyricss::*}`

**Comment by EnderDev** [comment]
<html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    Invalid HTTP Version &#x27;Invalid HTTP Version: &#x27;Blue - Rise ft. Jack &amp; Jack&amp;text_only=no HTTP/1.0&#x27;&#x27;
  </body>
</html>

**Comment by EnderDev** [comment]
`vbs<html>
  <head>
    <title>Bad Request</title>
  </head>
  <body>
    <h1><p>Bad Request</p></h1>
    Invalid HTTP Version &#x27;Invalid HTTP Version: &#x27;Blue - Rise ft. Jack &amp; Jack&amp;text_only=no HTTP/1.0&#x27;&#x27;
  </body>
</html>`

**Comment by btk5h** [comment]
You must escape unsafe characters in the url.
```
send a request to "https://api.ksoft.si/lyrics/search?q=%url safe ""Jonas Blue - Rise ft. Jack & Jack""%&text_only=no" with headers "User-Agent: Ender", "Content-Type: application/json" and "Authorization: Token ---"
```

**Comment by kierandrewett** [comment]
Now numbers don't work

**Comment by kierandrewett** [comment]
`send a request to url("https://api.ksoft.si/bans/check?user=197312811964170249") with headers "User-Agent: Ender", "Content-Type: application/json" and "Authorization: Token ---"
map json last response's body to {_bans::*}`

Just returns none, if I use a different API without numbers in the query, it works.
