### ISSUE TITLE
Nunbers dont work in params

### ISSUE THREAD

**Issue by kierandrewett** [btk5h/reqn#8]
Issue removed ORIGINAL GIT ID: 2dc287aa-6118-44c0-bf40-33bc9a0042f8

**Comment by kierandrewett** [comment]
`send a "GET" request to "https://api.ksoft.si/bans/check?user=217562587938816000" with headers "User-Agent: EnSGDFADFGADFGADFGDSFGSDAFGder" and "Authorization: Token ---"
map json last response's body to {_ban::*}`

Nothing is showing up. This might help http://i-hate.ender.site/i/zOKhm8.png

**Comment by btk5h** [comment]
Please provide more information. Have you tried replicating this request using an HTTP web request client? You may just be using their API incorrectly.
